In [62]:
import numpy as np

In [63]:
a = np.array([1,2,3])
print(a)
# ブロードキャスト
print(a * 3)
print(a + 2)

[1 2 3]
[3 6 9]
[3 4 5]


In [64]:
b = np.array([2,2,0])
print(a + b)
# print(a / b) # zero divided
print(a * b)

# 内積
np.dot(a,b)


[3 4 3]
[2 4 0]


6

In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# 始点、終点、間隔 に区切る 連番・等差数列
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [69]:
# 0~10まで15等分する 線形に等間隔な数列
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [72]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
c.shape

(2, 3)

In [74]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]])
d
# 3*3*3の3次元配列

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [75]:
d.shape

(2, 3, 3)

In [77]:
np.sum(c)

21

In [78]:
# 列ごとの和を求める
np.sum(c, axis=1)

array([ 6, 15])

In [79]:
# 配列の形状を変える
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [83]:
# 転置 行と列を変える
c.T
# np.transpose(c) # エイリアス

array([[1, 4],
       [2, 5],
       [3, 6]])

In [96]:
# 標準正規分布に従った値
np.random.randn()

0.2701651405861823

In [97]:
# 0~1まで
np.random.rand()

0.30297643582782485

In [100]:
# 任意の形状の配列の乱数
np.random.randn(2,3)

array([[-0.67730425,  0.77616387,  0.7462271 ],
       [ 0.3434881 ,  0.71760221, -0.39396159]])

In [103]:
np.random.rand(2,3)

array([[0.74910169, 0.8323331 , 0.04441398],
       [0.47862656, 0.80916627, 0.26812252]])

In [106]:
# インデックス
print(c)
print(c[0,0])
print(c[0,2])
print(c[1,2])

[[1 2 3]
 [4 5 6]]
1
3
6


In [112]:
# スライシング
d = np.array([0,5,2,7,1,9])
d

array([0, 5, 2, 7, 1, 9])

In [113]:
# 1~5未満の要素を取り出す(終点は含まれない))
d[1:5]

array([5, 2, 7, 1])

In [115]:
# [始点:終点:感覚]
d[0:5:2]

array([0, 2, 1])

In [116]:
# リバース
d[::to都to]

array([9, 1, 7, 2, 5, 0])

In [118]:
# ブロードキャスト
print(a)
print(c)
# a がcに合わせて形状が変わっている
print(a+c)
print(a*c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]


In [127]:
# numpyの演算速度
n = np.random.randn(10000000)
%timeit np.sum(a)

3.92 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [128]:
%timeit sum(n)

1.65 s ± 68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
