In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)
# ブロードキャスト
print(a * 3)
print(a + 2)

[1 2 3]
[3 6 9]
[3 4 5]


In [4]:
b = np.array([2,2,0])
print(a + b)
# print(a / b) # zero divided
print(a * b)

# 内積
np.dot(a,b)


[3 4 3]
[2 4 0]


6

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 始点、終点、間隔 に区切る 連番・等差数列
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
# 0~10まで15等分する 線形に等間隔な数列
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [8]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
c.shape

(2, 3)

In [10]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]])
d
# 3*3*3の3次元配列

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
d.shape

(2, 3, 3)

In [12]:
np.sum(c)

21

In [13]:
# 列ごとの和を求める
np.sum(c, axis=1)

array([ 6, 15])

In [14]:
# 配列の形状を変える
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
# 転置 行と列を変える
c.T
# np.transpose(c) # エイリアス

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
# 標準正規分布に従った値
np.random.randn()

-1.114618910757451

In [18]:
# 0~1まで
np.random.rand()

0.27992943404747206

In [19]:
# 任意の形状の配列の乱数
np.random.randn(2,3)

array([[-0.88401342, -0.67192783, -0.2060301 ],
       [ 0.94546149,  0.63665346, -1.19994162]])

In [20]:
np.random.rand(2,3)

array([[0.82761346, 0.76359957, 0.62046842],
       [0.07524389, 0.64384184, 0.55982541]])

In [21]:
# インデックス
print(c)
print(c[0,0])
print(c[0,2])
print(c[1,2])

[[1 2 3]
 [4 5 6]]
1
3
6


In [22]:
# スライシング
d = np.array([0,5,2,7,1,9])
d

array([0, 5, 2, 7, 1, 9])

In [23]:
# 1~5未満の要素を取り出す(終点は含まれない))
d[1:5]

array([5, 2, 7, 1])

In [24]:
# [始点:終点:感覚]
d[0:5:2]

array([0, 2, 1])

In [25]:
# リバース
d[::-1]

array([9, 1, 7, 2, 5, 0])

In [26]:
# ブロードキャスト
print(a)
print(c)
# a がcに合わせて形状が変わっている
print(a+c)
print(a*c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]


In [27]:
# numpyの演算速度
n = np.random.randn(10000000)
%timeit np.sum(a)

3.94 µs ± 54.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%timeit sum(n)

1.64 s ± 37.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
# 1画素あたり[R, G]の3*3画像から、左上2*2の画素配列を取得
ary = np.arange(18).reshape(3, 3, 2)
i = 0
mask = np.zeros((4, 2))
print(ary)
mask = ary[i:2, i:2].reshape(-1,2)
print(mask * 2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[[ 0  2]
 [ 4  6]
 [12 14]
 [16 18]]
